# -*- coding: utf-8 -*-
"""Exercise6_Issarapong_B_LAB_6796000245.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rkrvN_6aHlsimzwSnWtmHzPGgU1hNuR5
"""

student = ['Bob','Chalie','Michel','Mariah']

for stu in student:
  print(stu)
print('--------------')
for i in range(len(student)):
  print(student[i])

employees = {'Name':'Bob','Age': 25,'Gender':'Male'}

print(employees['Name'])
print(employees['Age'])
print(employees['Gender'])
print('---------------------')
for index, value in employees.items():
  print(index,value)

employees = [{'Name':'Bob','Age': 25,'Gender':'Male'},
             {'Name':'Chalie','Age': 28,'Gender':'Male'},
             {'Name':'Michel','Age': 38,'Gender':'Male'},
             {'Name':'Mariah','Age': 42,'Gender':'Female'}]

for emp in employees:
  for index, value in emp.items():
    print(index,value)
  print('---------------------')

import pandas as pd
employee_df = pd.DataFrame(employees) #method return dataframe from data

print(employee_df)

employee_df # call not print will show dataframe colab

employees = {'Name':['Bob','Chalie','Michael','Mariah'],
             'Age':[25,28,38,42],
             'Gender':['Male','Male','Male','Female']}

employee_df = pd.DataFrame(employees)
print(employee_df)

new_employee = {'Name':'Manee','Age': 31,'Gender':'Female'}
new_employee_df = pd.DataFrame([new_employee])
employee_df2= pd.concat([employee_df,new_employee_df],ignore_index=True)
print(employee_df2)

# new_employee2 = {'Name':['thanaton','pita','ice','anutin'],
#              'Age':[25,28,38,42],
#              'Gender':['Male','Male','Female','Male']}
new_employee2 = [{'Name':'thanaton','Age': 25,'Gender':'Male'},
             {'Name':'pita','Age': 28,'Gender':'Male'},
             {'Name':'ice','Age': 38,'Gender':'Male'},
             {'Name':'anutin','Age': 42,'Gender':'Female'}]


new_employee_df2 = pd.DataFrame(new_employee2)
employee_df3 = pd.concat([employee_df2, new_employee_df2], ignore_index=True)
print(employee_df3)

#employee_df.drop(1)
#employee_df.loc[0]
employee_df3 = employee_df3.drop(employee_df[employee_df3['Name']=='Bob'].index)
employee_df3.drop(employee_df3[employee_df3['Name']=='Bob'].index ,inplace=True)
employee_df3

medals = pd.read_csv('olympics.csv')
medals

#pd.set_option('display.max_rows', None) #show all row of df
pd.reset_option('display.max_rows') # reset display of df (default)
medals

medals.rename(columns={'Unnamed: 0':'CountryName'},inplace=True) #change name columns of df

medals.drop(columns=['Total','Total.1','№ Games','01 !.2','02 !.2','03 !.2','Combined total'], inplace=True)
medals

column_mapping ={'№ Summer': 'NumberofSummer',
                 '01 !':'SummerGold',
                 '02 !':'SummerSilver',
                 '03 !':'SummerBronze',
                 '№ Winter':'NumberofWinter',
                 '01 !.1':'WinterGold',
                 '02 !.1':'WinterSilver',
                 '03 !.1':'WinterBronze',}# rename use Dictonary
medals.rename(columns=column_mapping,inplace=True)
medals

medals.drop(index=146,inplace=True)
medals

medals['CountryName'].str.split('(',expand=True)[1].str.split(')',expand=True)[0] # Split code of Country select symbol column 1
medals['CountryCode'] = medals['CountryName'].str.split('(',expand=True)[1].str.split(')',expand=True)[0]
medals

medals['CountryName'].str.split('(',expand=True)[0]
medals['CountryName'] = medals['CountryName'].str.split('(',expand=True)[0] # Split name Country by symbol and collect Country
medals

medals[["CountryCode","CountryName"]]

current_columns = medals.columns.tolist() # Get a list of all current column names
current_columns.remove('CountryCode') # Remove 'CountryCode' from its current position in the list
new_column_order = ['CountryCode'] + current_columns # Create a new list with 'CountryCode' at the beginning, followed by the rest of the columns
medals = medals[new_column_order] # Reindex the DataFrame with the new column order
medals

medals['CountryCode'].is_unique
medals['CountryCode'].isna()

# medals.loc[0] #show location index
# medals.loc[0,'CountryName'] # select Row  0 of column CountryName
# medals.loc[[0,2,100,120]] #  Row 0,2,100,120
# medals.loc[[0,2,100,120],['CountryCode','CountryName','SummerGold']] #select mutiple  Row  and column
# medals.loc[5:10] # select row of range
# medals.loc[100:105,['CountryCode','CountryName','SummerGold']] #select row of range and column
# medals.loc[100:105,'CountryCode':'SummerGold'] #select row of range and column
medals.loc[medals['SummerGold']>=100 ,['CountryName','SummerGold']] #select row of range and column add condition

medals.set_index('CountryCode', inplace=True)# Set 'CountryCode' as the index of the DataFrame
medals # Display the DataFrame with the new index

# medals['NumberofSummer'].max()
medals.loc[medals['NumberofSummer']==medals['NumberofSummer'].max() ,['CountryName','NumberofSummer','SummerGold']]

medals.loc[medals['NumberofWinter']==medals['NumberofWinter'].max() ,['CountryName','NumberofWinter','SummerGold']]

# (medals['WinterGold'] + medals['WinterSilver'] + medals['WinterBronze']).sum()
medals[['WinterGold','WinterSilver','WinterBronze']].sum().sum()

asean_medals = medals.loc[['THA','SIN','INA','PHI','VIE','MAS']]
asean_medals

asean_medals['TotalSummer'] = asean_medals['SummerGold'] + asean_medals['SummerSilver']+ asean_medals['SummerBronze']
asean_medals['TotalWinter'] = asean_medals['WinterGold'] + asean_medals['WinterSilver']+ asean_medals['WinterBronze']
asean_medals = asean_medals.loc[:, ["CountryName", "TotalSummer", "TotalWinter"]]
asean_medals

medals.loc[medals['CountryName'].str.startswith('A'),'CountryName':'SummerBronze']

medals['Summertotal'] = medals['SummerGold'] + medals['SummerSilver']+ medals['SummerBronze']
medals['Wintertotal'] = medals['WinterGold'] + medals['WinterSilver']+ medals['WinterBronze']
medals

medals.loc[medals['Wintertotal']>medals['Summertotal']]
medalstotal = medals.loc[medals['Wintertotal']>medals['Summertotal'],['CountryName','Summertotal','Wintertotal']]
medalstotal

medals.loc[(medals['Wintertotal']==0)&(medals['Summertotal']!=0)]
medalstotalcondition = medals.loc[(medals['Wintertotal']==0)&(medals['Summertotal']!=0) ,['CountryName','Summertotal','Wintertotal']]
medalstotalcondition

medals['Score'] = medals['SummerGold']*3 + medals['SummerSilver']*2 + medals['SummerBronze']*1
medals

medals['Score'] = medals['SummerGold']*3 + medals['SummerSilver']*2 + medals['SummerBronze']*1
medalstop10 = medals.sort_values(by='Score', ascending=False).head(10)
medalstop10 = medalstop10[['CountryName','Score']]
medalstop10

medals['perGame'] = medals['Score'] / (medals['NumberofSummer'] + medals['NumberofWinter'])
medals

medals['perGame'] = medals['Score'] / (medals['NumberofSummer'] + medals['NumberofWinter'])
medalstop10perGame = medals.sort_values(by='perGame', ascending=False).head(10)
medalstop10perGame = medalstop10perGame[['CountryName','perGame']]
medalstop10perGame

medals2 = medals
germany_rows = medals2[medals2['CountryName'].str.contains('Germany')]
germany_rows
all_germany = germany_rows.sum(numeric_only=True)
all_germany['CountryName'] = 'All Germany'
all_germany
medals2 = medals2.drop(germany_rows.index)
medals2 = pd.concat([medals2, pd.DataFrame([all_germany])], ignore_index=True)
medal2stop10 = medals2.sort_values(by='Score', ascending=False).head(10)
medal2stop10 = medal2stop10[['CountryName','Score']]
medal2stop10

medals2top10perGame = medals2.sort_values(by='perGame', ascending=False).head(10)
medals2top10perGame = medals2top10perGame[['CountryName','perGame']]
medals2top10perGame

# @title
medals2 = pd.read_csv('olympics.csv')
medals2.rename(columns={'Unnamed: 0':'CountryName'},inplace=True) #change name columns of df
medals2.drop(columns=['Total','Total.1','№ Games','01 !.2','02 !.2','03 !.2'], inplace=True)
column_mapping ={'№ Summer': 'NumberofSummer',
                 '01 !':'SummerGold',
                 '02 !':'SummerSilver',
                 '03 !':'SummerBronze',
                 '№ Winter':'NumberofWinter',
                 '01 !.1':'WinterGold',
                 '02 !.1':'WinterSilver',
                 '03 !.1':'WinterBronze',}# rename use Dictonary
medals2.rename(columns=column_mapping,inplace=True)
medals2.drop(index=146,inplace=True)
medals2['CountryName'].str.split('(',expand=True)[1].str.split(')',expand=True)[0] # Split code of Country select symbol column 1
medals2['CountryCode'] = medals2['CountryName'].str.split('(',expand=True)[1].str.split(')',expand=True)[0]
medals2.set_index('CountryCode', inplace=True)# Set 'CountryCode' as the index of the DataFrame
medals2

#Follow ajan 22. index
new_row = medals.loc[medals['CountryName'].str.contains('Germany'),:].sum()
new_row['CountryName'] = 'All Germany'
new_row.name='GER'
# pd.concat([medals, pd.DataFrame([new_row])])
germany_rows = medals[medals['CountryName'].str.contains('Germany')]
germanydrop=medals.drop(germany_rows.index)
germanydrop[germanydrop['CountryName'].str.contains('Germany')]
medals_allgermany=pd.concat([germanydrop, pd.DataFrame([new_row])])
medals_allgermany

#Follow ajan 23. index
medal2stop10 = medals_allgermany.sort_values(by='Score', ascending=False).head(10)
medal2stop10 = medal2stop10[['CountryName','Score']]
medal2stop10

medals2top10perGame = medals_allgermany.sort_values(by='perGame', ascending=False).head(10)
medals2top10perGame = medals2top10perGame[['CountryName','perGame']]
medals2top10perGame

drinks_df = pd.read_csv('drinks.csv')
drinks_df

drinks_df.groupby('continent')['total_litres_of_pure_alcohol'].mean()

medals['CountryName'] = medals['CountryName'].str.strip()

medals.join(drinks_df.set_index('country')['continent'], on='CountryName')