# -*- coding: utf-8 -*-
"""Issarapong B..ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10HyzagYtOh2lAX85AQnw6lNEpEzY2KzY
"""

import pandas as pd
import matplotlib.pyplot as plt

# 1. อ่านข้อมูล
url = 'https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/drinks.csv'
df = pd.read_csv(url)

# 2. หาค่าเฉลี่ยโดยระบุ numeric_only=True เพื่อข้ามคอลัมน์ที่เป็นข้อความ (เช่น country)
continent_avg = df.groupby('continent').mean(numeric_only=True)

# 3. แสดงผลข้อมูลเพื่อตรวจสอบ
print(continent_avg)

# 4. พล็อตกราฟแท่งตามภาพที่ 2.13
continent_avg.plot(kind='bar')
plt.ylabel('Average Servings')
plt.title('Average Beverage Consumption by Continent')
plt.show()

