# -*- coding: utf-8 -*-
"""Issarapong B..ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10HyzagYtOh2lAX85AQnw6lNEpEzY2KzY
"""

import seaborn as sns
import matplotlib.pyplot as plt

tips = sns.load_dataset('tips')
sns.boxplot(x='day', y='total_bill', hue='sex', data=tips)

# 3. แสดงผลกราฟ
plt.title('Box plot of total_bill by day and sex')
plt.show()