# -*- coding: utf-8 -*-
"""Issarapong B..ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10HyzagYtOh2lAX85AQnw6lNEpEzY2KzY
"""
import pandas as pd

# 1. เตรียมข้อมูลในรูปแบบ Dictionary
data = {
    'name': ['Jairak', 'Mana', 'Sansuk', 'Wirat'],
    'age': [30, 50, 60, 10],
    'height': [1.79, 1.60, 1.80, 1.35],
    'medical_condition': [
        ['high blood pressure', 'diabetes', 'chronic kidney'],
        ['high cholesterol', 'migrain'],
        ['low blood pressure', 'asthma'],
        ['anemia']
    ]
}

# 2. กำหนด Index ตามภาพ
index = [1111, 1112, 1113, 1114]

# 3. สร้าง DataFrame
df = pd.DataFrame(data, index=index)

# แสดงผลตรวจสอบ
print(df)

