# -*- coding: utf-8 -*-
"""Issarapong B..ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10HyzagYtOh2lAX85AQnw6lNEpEzY2KzY
"""

import random
import datetime

# --- Data Storage ---
# เก็บข้อมูลสมาชิกทั้งหมด { 'username': {ข้อมูลสมาชิก} }
all_members = {}

def registration():
    print("\n" + "#"*20)
    print("   Registration")
    print("#"*20)
    name = input("Name -> ")
    email = input("Email -> ")
    mobile = input("Mobile no. -> ")
    username = input("username -> ")
    password = input("password -> ")

    if username in all_members:
        print("\nError: This username is already taken!")
    else:
        all_members[username] = {
            "name": name,
            "email": email,
            "mobile": mobile,
            "password": password,
            "accounts": {}  # เก็บข้อมูลบัญชี
        }
        print("#"*20)
        print("User added successfully")
        print("#"*20)

def login():
    print("\n" + "#"*7 + " Login " + "#"*7)
    user_input = input("username -> ")
    pass_input = input("password -> ")

    if user_input in all_members and all_members[user_input]['password'] == pass_input:
        print("#" * 25)
        print("Login Successfully")
        print("#" * 25)
        user_menu(user_input)
    else:
        print("\nInvalid username or password!")

def user_menu(username):
    while True:
        user_info = all_members[username]
        num_accounts = len(user_info['accounts'])
        total_balance = sum(acc['balance'] for acc in user_info['accounts'].values())

        print("\n" + "#"*10 + " User Information " + "#"*10)
        print(f"Name -> {user_info['name']}")
        print(f"The number of Accounts -> {num_accounts}")
        print(f"Total Balance -> {total_balance:,.1f}")
        print("#" * 38)

        print("\n" + "#"*10 + " User Menu " + "#"*10)
        print("1 -> Open Account")
        print("2 -> Show Account")
        print("9 -> Logout")
        print("#" * 31)

        choice = input("Your Choice -> ")
        if choice == '1':
            open_account(username)
        elif choice == '2':
            show_account_detail(username)
        elif choice == '9':
            break

def open_account(username):
    print("\n" + "="*7 + " Open Account " + "="*7)
    while True:
        new_acc_no = "".join([str(random.randint(0, 9)) for _ in range(9)])
        exists = any(new_acc_no in m['accounts'] for m in all_members.values())
        if not exists: break

    all_members[username]['accounts'][new_acc_no] = {"balance": 0.0, "transactions": []}
    print("Account is open successfully")
    print("="*28)

def show_account_detail(username):
    while True:
        user_info = all_members[username]
        acc_dict = user_info['accounts']
        total_bal = sum(acc['balance'] for acc in acc_dict.values())

        print("\n### Account Detail ###")
        print(f"Name : {user_info['name']}")
        print(f"Total Balance : {total_bal:,.1f}")
        print("+++++ Account Menu ++++++")

        acc_list = list(acc_dict.keys())
        for i, acc_no in enumerate(acc_list, 1):
            print(f"{i} -> {acc_no} : Balance = {acc_dict[acc_no]['balance']:,.1f}")
        print("9 -> quit")
        print("+" * 25)

        choice = input("Your choice -> ")
        if choice == '9': break
        if choice.isdigit() and 1 <= int(choice) <= len(acc_list):
            transaction_menu(username, acc_list[int(choice)-1])

def transaction_menu(username, acc_no):
    while True:
        print(f"\n---Transaction Menu For Account {acc_no}---")
        print("1 -> Show Balance\n2 -> Deposit\n3 -> Withdraw\n4 -> Transfer\n5 -> Show Statement\n9 -> Exit")
        choice = input("Your choice -> ")

        if choice == '1':
            bal = all_members[username]['accounts'][acc_no]['balance']
            print(f"\nThe balance of Account no. {acc_no} : {bal:,.1f} baht")
        elif choice == '2':
            deposit(username, acc_no)
        elif choice == '3':
            withdraw(username, acc_no)
        elif choice == '4':
            transfer(username, acc_no)
        elif choice == '5':
            show_statement(username, acc_no)
        elif choice == '9': break

def deposit(username, acc_no):
    print(f"\n==== Deposit To {acc_no} ====")
    try:
        amt = float(input("Input amount to deposit -> "))
        rem = input("Input remark -> ")
        all_members[username]['accounts'][acc_no]['balance'] += amt
        # ฝากเงิน
        all_members[username]['accounts'][acc_no]['transactions'].append({
            "ts": datetime.datetime.now(), "type": "Deposit", "amt": amt, "rem": rem, "target": "null"
        })
    except: print("Invalid input!")

def withdraw(username, acc_no):
    bal = all_members[username]['accounts'][acc_no]['balance']
    print(f"\n===== Withdraw From {acc_no} =====")
    try:
        amt = float(input(f"Input amount to withdraw (<= {bal} or 0 to exit) -> "))
        if amt == 0: return
        if amt > bal: print("Error: Insufficient funds")
        else:
            rem = input("Input remark -> ")
            all_members[username]['accounts'][acc_no]['balance'] -= amt
            # ถอนเงิน
            all_members[username]['accounts'][acc_no]['transactions'].append({
                "ts": datetime.datetime.now(), "type": "Withdraw", "amt": -amt, "rem": rem, "target": "null"
            })
    except: print("Invalid input!")

def transfer(username, from_acc):
    bal = all_members[username]['accounts'][from_acc]['balance']
    print(f"\n===== Transfer From {from_acc} =====")
    to_acc = input("Input destination account no. (input 0 to exit) -> ")
    if to_acc == '0': return

    target_user = next((u for u, d in all_members.items() if to_acc in d['accounts']), None)
    if not target_user:
        print("Error: Account not found")
        return

    try:
        amt = float(input(f"Input amount to {to_acc} (<= {bal}) -> "))
        if amt > bal: print("Error: Insufficient funds")
        else:
            rem = input("Input remark -> ")
            # ฝั่งโอน
            all_members[username]['accounts'][from_acc]['balance'] -= amt
            all_members[username]['accounts'][from_acc]['transactions'].append({
                "ts": datetime.datetime.now(), "type": "Transfer", "amt": -amt, "rem": rem, "target": to_acc
            })
            # ฝั่งรับ
            all_members[target_user]['accounts'][to_acc]['balance'] += amt
            all_members[target_user]['accounts'][to_acc]['transactions'].append({
                "ts": datetime.datetime.now(), "type": "Receive", "amt": amt, "rem": rem, "target": from_acc
            })
            print("Transfer successful!")
    except: print("Invalid input!")

# แก้ไขฟังก์ชัน Show Statement ให้แสดงทั้งหมดทันที
def show_statement(username, acc_no):
    print(f"\n****** Statement for Account {acc_no} ******")
    txns = all_members[username]['accounts'][acc_no]['transactions']

    if not txns:
        print("No transactions found.")
    else:
        count = 1
        for t in txns:
            # แสดงรูปแบบลำดับ) ==> วันเวลาISO: จำนวนเงิน : หมายเหตุ : บัญชีปลายทาง
            print(f"{count}) ==> {t['ts'].isoformat()}: {t['amt']:.1f} : {t['rem']} : {t['target']}")
            count += 1

    print("*" * 45)

# --- จุดเริ่มต้นโปรแกรม ---
def main():
    while True:
        print("\n" + "#"*20 + "\n   Main Menu\n" + "#"*20)
        print("1 -> Registration\n2 -> Login\n9 -> Exit")
        choice = input("Your Choice -> ")
        if choice == '1': registration()
        elif choice == '2': login()
        elif choice == '9': break

if __name__ == "__main__":
    main()